apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        image: us-docker.pkg.dev/gen-lang-client-0683956833/hello-world/latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000