# Use official Node.js runtime
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

########
# Expose port
EXPOSE 8080

# Start app
CMD [ "node", "app/app.js" ]