name: Deploy to GKE

on:
  push:
    paths:
      - 'app/**'
      - 'k8s/**'
  workflow_run:
    workflows: ["Build and Push App Container"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials basic-gke-cluster \
            --region us-east1 \
            --project gen-lang-client-0683956833

      - name: Deploy Application
        run: kubectl apply -f k8s/