name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.0'  # Specify your desired version

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          
      - name: Check if GCP_SA_KEY is set
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY is not set"
          else
            echo "GCP_SA_KEY is set"
          fi      

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true
          create_credentials_file: true

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve tfplan