name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
      - name: Check if GCP_SA_KEY is set
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY is not set"
          else
            echo "GCP_SA_KEY is set"
          fi      

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy GKE Cluster
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve